matrix:
  include:
    - language: node_js
      script: npm run test:node
      node_js: "stable"
      env: 
        - NAME="Node stable"
    - language: node_js
      script: npm run test:node
      node_js: "7.10"
      env: 
        - NAME="Node 7"
    - language: node_js
      script: npm run test:node
      node_js: "6.11"
      env: 
        - NAME="Node 6"
    - language: node_js
      node_js: "7.10"
      sudo: required
      env: 
        - NAME="Web"
      addons:
        firefox: latest
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3 # give xvfb some time to start
      script: npm run test:web

